version: "3"

services:
  spring1:
    build:
      context: ${PWD}/demo3
      dockerfile: ${PWD}/demo3/Dockerfile
    ports:
      - 8080:8080

  spring2:
    build:
      context: ${PWD}/demo4
      dockerfile: ${PWD}/demo4/Dockerfile
    ports:
      - 8080:8080
